export const SEARCH_TYPE_TITLE = "SEARCH_TYPE_TITLE";
export const SEARCH_TYPE_CONTENT = "SEARCH_TYPE_CONTENT";

export const MODAL_TYPE_ALERT = "MODAL_TYPE_ALERT";
export const MODAL_TYPE_CONFIRM = "MODAL_TYPE_CONFIRM";
